### ISSUE TITLE
No schema selected?

### ISSUE THREAD

**Issue by marccampbell** [db-migrate/cockroachdb#1]
When I try to run `db-migrate up` using this, I'm getting this error. Are there docs showing how to use this library?

```
$ db-migrate up
[ERROR] AssertionError [ERR_ASSERTION]: ifError got unwanted exception: no schema has been selected to create "migrations" in
    at module.exports (/src/src/node_modules/db-migrate/lib/commands/helper/assert.js:9:14)
    at /src/src/node_modules/db-migrate/lib/commands/up.js:29:16
    at tryCatcher (/src/src/node_modules/bluebird/js/release/util.js:16:23)
    at Promise.errorAdapter (/src/src/node_modules/bluebird/js/release/nodeify.js:35:34)
    at Promise._settlePromise (/src/src/node_modules/bluebird/js/release/promise.js:566:21)
    at Promise._settlePromise0 (/src/src/node_modules/bluebird/js/release/promise.js:614:10)
    at Promise._settlePromises (/src/src/node_modules/bluebird/js/release/promise.js:689:18)
    at Async._drainQueue (/src/src/node_modules/bluebird/js/release/async.js:133:16)
    at Async._drainQueues (/src/src/node_modules/bluebird/js/release/async.js:143:10)
    at Immediate.Async.drainQueues [as _onImmediate] (/src/src/node_modules/bluebird/js/release/async.js:17:14)
    at runCallback (timers.js:696:18)
    at tryOnImmediate (timers.js:667:5)
    at processImmediate (timers.js:649:5)
    at Connection.parseE (/src/src/node_modules/pg/lib/connection.js:553:11)
    at Connection.parseMessage (/src/src/node_modules/pg/lib/connection.js:378:19)
    at Socket.<anonymous> (/src/src/node_modules/pg/lib/connection.js:119:22)
    at Socket.emit (events.js:182:13)
    at addChunk (_stream_readable.js:283:12)
    at readableAddChunk (_stream_readable.js:264:11)
    at Socket.Readable.push (_stream_readable.js:219:10)
    at TCP.onread (net.js:635:20)
```

**Comment by wzrdtales** [comment]
Your database.json is most probably not correctly setup. Check your configuration, look in the docs for examples.
